version: "3.9"
services:
  app: 
    build: .
    restart: always
    environment:
      - APP_PORT=8080
      - REDIS_CONNECTION_STRING=redis://redis:6379/0
      - JWT_SECRET=fdkslhfdshgjldsngklds
      - JWT_EXPIRATION=48h
      - DATABASE_HOST=localhost
      - DATACENTER=datacenter1
      - KEYSPACE=miniurl
    ports:
      - '8080:8080'
    expose:
      - '8080'

  cassandra:
      image: cassandra:3.11.2
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      volumes:
        - ./out/cassandra_data:/var/lib/cassandra
      healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    # depends_on: 
      
    networks:
      - miniurl

networks:
  miniurl:
    name: miniurl
    driver: bridge

volumes:
  cache:
    driver: local