version: "3.9"
services:
  app: 
    build: .
    restart: always
    environment:
      - APP_PORT=8080
      - REDIS_CONNECTION_STRING=redis://redis:6379/0
      - JWT_SECRET=fdkslhfdshgjldsngklds
      - JWT_EXPIRATION=48h
      - DATABASE_HOST=cassandra
      - DATACENTER=datacenter1
      - KEYSPACE=miniurl
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - cassandra
      - redis
      - init
    networks:
      - miniurl

  cassandra:
      image: cassandra:4.1.0
      container_name: cassandra
      ports:
        - "9042:9042"
      expose:
      - '9042'
      restart: "no"
      volumes:
        - db:/var/lib/cassandra
      networks:
        - miniurl
  init:
    image: cassandra:4.1.0
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: ["/init.sh"]
    volumes:
      - ./init.sh:/init.sh



  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      
    networks:
      - miniurl

networks:
  miniurl:
    name: miniurl
    driver: bridge

volumes:
  db:
    driver: local
  cache:
    driver: local