version: "3.9"
services:
  app: 
    build: .
    restart: always
    environment:
      - REDIS_CONNECTION_STRING=redis://redis:6379/0
      - JWT_SECRET=fdkslhfdshgjldsngklds
      - DATABASE_HOST=cassandra
      - DATACENTER=datacenter1
      - KEYSPACE=system
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - cassandra
      - redis
    networks:
      - miniurl

  cassandra:
    image: cassandra:4.1.0
    container_name: cassandra
    ports:
      - "9042:9042"
    expose:
    - '9042'
    restart: on-failure:10
    volumes:
      - db:/var/lib/cassandra
    networks:
      - miniurl
    # healthcheck:
    #   test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 10


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      
    networks:
      - miniurl

networks:
  miniurl:
    name: miniurl
    driver: bridge

volumes:
  db:
    driver: local
  cache:
    driver: local